name: "Markdown Lint"
on: push
concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash


jobs:

  md-link-check:
    name: "Check for broken links"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Needed to restrict checks only to changed files

      - name: Run Markdown link check
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          # Exclude email addresses and other common request errors from link check
          config-file: '.github/linters/mlc_config.json' 
          use-quiet-mode: 'yes'
          base-branch: 'master'
          check-modified-files-only: 'yes'

  super-lint:
    name: "Check for broken Markdown"
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Needed to restrict checks only to changed files
    
    - name: Run markdownlint
      uses: github/super-linter/slim@v4
      env:
        IGNORE_GITIGNORED_FILES: true
        DEFAULT_BRANCH: master
        LINTER_RULES_PATH: '.github/linters'
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        LOG_LEVEL: WARN
        VALIDATE_ALL_CODEBASE: false # Only check new or edited files
        MULTI_STATUS: true
        DISABLE_ERRORS: true
        VALIDATE_MARKDOWN: true
